### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by AggFerret** [ProdByPengu/Lithiums-Icetea-Styled-GUI#1]
this is so clean omg how clean code???!??!!!!! i love this 🥵🥵🥵😍😍😍😍 it's so beautiful

**Comment by ProdByPengu** [comment]
nah the code looks so fucking ass, made this a while ago. Before the start of lithium lmao

**Comment by AggFerret** [comment]
it was a joke fucking retard

**Comment by ProdByPengu** [comment]
oh trust me, i know
